Update nginx to 1.24.0
getsentry/self-hosted pull request #2235
Opened 2023-06-26 17:11 UTC by williamdes

LGTM the changelog: https://nginx.org/en/CHANGES-1.24
1.23 LGTM: https://nginx.org/en/CHANGES
and 1.22 only had a .1 with CVE fixes

1.25 is still a bit new, maybe we should wait before bumping: https://endoflife.date/nginx

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2023-06-26 18:09 UTC, williamdes commented
Gosh the CI is flaky: https://github.com/getsentry/self-hosted/actions/runs/5381345860/jobs/9765286778#step:4:12472

2023-06-28 07:19 UTC, aminvakil requested changes
We have a very simple use of nginx and I don't think we will face a problem using 1.25.1, let's bump it to latest version.

2023-06-28 10:28 UTC, aminvakil commented
Can you also please correct the PR title?

2023-06-28 15:39 UTC, aminvakil approved these changes

2023-06-28 17:25 UTC, hubertdeng123 approved these changes

2023-06-30 18:36 UTC, merged